const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
const FETCH_BOOKS_REQUST = "FETCH_BOOKS_REQUST";
const FETCH_BOOKS_FAILUR = "FETCH_BOOKS_FAILUR";
const BOOK_ADDED_TO_CART = "BOOK_ADDED_TO_CART";

export {
  FETCH_BOOKS_SUCCESS,
  FETCH_BOOKS_REQUST,
  FETCH_BOOKS_FAILUR,
  BOOK_ADDED_TO_CART
};
